#!/usr/bin/env python3
"""Render docs/repositories.md from data/repositories.json.

The JSON is the single source of truth for the repository catalogue; it is also
consumed by the community site. Run this after editing it:

    python tools/gen_repositories.py
"""
import json
import os
import textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'repositories.json')
OUT = os.path.join(ROOT, 'docs', 'repositories.md')

ANCHOR = {
    'core-clients': 'core-clients',
    'product-clients': 'product-client-libraries',
    'services': 'services',
    'node-red': 'node-red-nodes',
    'tooling': 'tooling-and-scaffolding',
    'infra': 'containers-and-environments',
    'specs': 'specifications-and-schemas',
}

HEADER = """\
# Repositories

Every OpenDXL repository, grouped by what it does. All of them are Apache-2.0 unless the
table says otherwise. The upstream projects live under
[github.com/opendxl](https://github.com/opendxl); the SIEM sensor is new work of this fork
and has no upstream counterpart.

The version shown is the version declared in the repository, which for most of these is also
the last published release. Read [Compatibility](compatibility.md) before pinning any of them.

<!-- Generated by tools/gen_repositories.py from data/repositories.json. Do not edit by hand. -->
"""


def main():
    data = json.load(open(DATA, encoding='utf-8'))
    repos = data['repositories']
    lines = [HEADER]

    for group in data['groups']:
        key = group['key']
        rows = [r for r in repos if r['group'] == key]
        lines.append('## %s\n' % group['title'])
        lines.append(group['blurb'] + '\n')
        for r in rows:
            desc = ' '.join(r['description'].split())
            if len(desc) > 320:
                desc = desc[:317].rsplit(' ', 1)[0] + '…'
            meta = [r['language']]
            if r['version']:
                meta.append('v' + r['version'])
            meta.append(r['license'])
            lines.append('### [%s](%s)\n' % (r['name'], r['url']))
            lines.append('*%s*\n' % ' · '.join(meta))
            lines.append(textwrap.fill(desc, 92) + '\n')

    open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
    print('wrote %s (%d repositories)' % (OUT, len(repos)))


if __name__ == '__main__':
    main()
