#!/usr/bin/env python3
"""Render docs/fork.md from data/fork-changes.json.

The JSON is produced from the actual git history of the maintained fork, so this page
cannot drift from what was really committed. Regenerate after new work lands:

    python tools/gen_fork.py
"""
import json
import os
import textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'fork-changes.json')
OUT = os.path.join(ROOT, 'docs', 'fork.md')

GROUP_TITLE = [
    ('core-clients', 'Core clients'),
    ('product-clients', 'Product client libraries'),
    ('services', 'Services'),
    ('node-red', 'Node-RED nodes'),
    ('tooling', 'Tooling and scaffolding'),
    ('infra', 'Broker, containers and environments'),
    ('specs', 'Specifications and schemas'),
]

KIND_LABEL = {
    'bug': 'bug fix',
    'security': 'security',
    'feature': 'feature',
    'tests': 'tests',
    'deps': 'dependencies',
    'ci': 'CI',
    'docs': 'docs',
}
# Order for the per-repo listing: the interesting things first.
KIND_ORDER = ['security', 'bug', 'feature', 'deps', 'tests', 'ci', 'docs']


def header(data):
    t = data['totals']
    by = t['by_kind']
    return """# The maintained fork

Upstream OpenDXL is maintained, but unevenly. The core clients still see occasional
releases from Trellix engineers - the Python client 5.7.0.1 in January 2025, the Java client
0.2.9 in July 2025, the Databus client 2.7.0 in May 2025 with CVE fixes as late as July 2026.
The roughly thirty integration and service repositories have had no commit since 2019-2021.
Nothing is archived, so from the outside it is hard to tell which of the two a given
repository is. The work described on the [compatibility page](compatibility.md) — the TLS fixes, the MessagePack compatibility, the
Python 3.12+ and JDK 21 support — lives in a **maintained fork of all %(total)d
repositories**.

- **Maintainer:** [@%(author)s](https://github.com/%(author)s). Every change below was
  written, tested and pushed by that account.
- **Where the repositories are hosted:** the forks currently sit under the personal GitHub
  account [`%(owner)s`](https://github.com/%(owner)s), with `%(author)s` as a collaborator
  with push rights. The hosting account is an artefact of how the forks were first created;
  the maintainer is `%(author)s`. Moving them to `%(author)s` or to an organisation is an
  open question, not a change of ownership of the work.
- **Released, but not to the public registries.** Every core client has tagged releases with
  built artifacts, and the broker image is on GHCR. Nothing goes to PyPI, npmjs.com or Maven
  Central: those namespaces belong to the upstream project — see
  [Using the fork](#using-the-fork).

<!-- Generated by tools/gen_fork.py from data/fork-changes.json. Do not edit by hand. -->

## What changed, in numbers

%(commits)d commits across **%(touched)d of %(total)d repositories**. Two were left alone:
`opendxl-api-specification` (a 2019 draft whose external `$ref` no longer resolves) and
`opendxl-build-status`.

| Kind | Commits | What it means |
|---|---|---|
| Security | %(security)d | TLS defaults and options, removed vulnerable pins, a plaintext download made HTTPS |
| Bug fixes | %(bug)d | Defects that make the published code fail on a current runtime or return wrong results |
| Build and packaging | %(feature)d + %(deps)d | Python 3.8–3.14, JDK 8–21 branch lines, current base images, dependency updates |
| Tests | %(tests)d | New unit tests, mostly where a fix needed one to hold |
| CI | %(ci)d | Working GitHub Actions instead of `python setup.py test` |
| Docs | %(docs)d | READMEs that no longer describe the code |

""" % {
        'author': data['author'], 'owner': data['fork_owner_account'],
        'commits': t['commits'], 'touched': t['repositories_touched'],
        'total': t['repositories_total'],
        'security': by.get('security', 0), 'bug': by.get('bug', 0),
        'feature': by.get('feature', 0), 'deps': by.get('deps', 0),
        'tests': by.get('tests', 0), 'ci': by.get('ci', 0), 'docs': by.get('docs', 0),
    }


def highlights(data):
    """The security and bug commits, which are the reason the fork exists."""
    rows = []
    for kind in ('security', 'bug'):
        for repo in data['repositories']:
            for commit in repo['commits']:
                if commit['kind'] == kind:
                    rows.append((KIND_LABEL[kind], repo['name'], commit['subject']))
    intro = ('The full list of the %d commits that fix a defect or harden something, as '
             'opposed to updating a dependency or a workflow. Everything else is in the '
             'per-repository listing below.' % len(rows))
    out = ['## Security and correctness fixes\n',
           textwrap.fill(intro, 92) + '\n',
           '| Kind | Repository | Change |',
           '|---|---|---|']
    for kind, repo, subject in rows:
        out.append('| %s | `%s` | %s |' % (kind, repo, subject.replace('|', r'\|')))
    out.append('')
    return '\n'.join(out)


def per_repo(data):
    out = ['## Every change, by repository\n']
    by_group = {}
    for repo in data['repositories']:
        by_group.setdefault(repo['group'], []).append(repo)

    for key, title in GROUP_TITLE:
        repos = [r for r in by_group.get(key, []) if r['commits']]
        if not repos:
            continue
        out.append('### %s\n' % title)
        for repo in repos:
            branches = ''
            if repo['extra_branches']:
                branches = ' · branches: %s' % ', '.join(
                    '`%s`' % b for b in ['(default) ' + repo['default_branch']] +
                    repo['extra_branches'])
            # Link the fork, not upstream: this page is about what the fork changed.
            out.append('**[%s](https://github.com/%s/%s)** — %d commits%s\n'
                       % (repo['name'], data['fork_owner_account'], repo['name'],
                          len(repo['commits']), branches))
            ordered = sorted(repo['commits'],
                             key=lambda c: KIND_ORDER.index(c['kind'])
                             if c['kind'] in KIND_ORDER else 99)
            for commit in ordered:
                out.append('- *%s* — %s' % (KIND_LABEL[commit['kind']], commit['subject']))
            out.append('')
    return '\n'.join(out)


FOOTER = """## Using the fork

Each core client now has releases: a tag builds the artifacts, publishes them where the
namespace allows it, and attaches them to a release page. **Nothing is published to PyPI,
npmjs.com or Maven Central** - those namespaces belong to the upstream project, and a fork
occupying a namespace it does not own is the supply-chain problem described on the
[security page](security.md#package-names-are-a-security-boundary). The artifacts keep the
upstream names so they drop into an existing install, and carry a `fork.n` version marker so
the two cannot be confused.

**Python** - the wheel from the [releases](https://github.com/%(owner)s/opendxl-client-python/releases),
or straight from git:

```bash
pip install "git+https://github.com/%(owner)s/opendxl-client-python@epo-legacy#egg=dxlclient"
pip install "git+https://github.com/%(owner)s/opendxl-bootstrap-python@master#egg=dxlbootstrap"
```

The distribution is called `dxlclient` and versioned `5.7.0.1+fork.1`; a local version
identifier still satisfies the plain `dxlclient` dependency the downstream OpenDXL projects
declare, which is what takes them off the `msgpack<1.0.0` pin of the published package, and
`pip list` shows which build is installed.

**Install order matters.** Put the fork's client (and `dxlbootstrap`) in the environment
*before* the project that depends on it - pip then finds the requirement already satisfied and
never asks PyPI:

```bash
pip install "dxlclient @ git+https://github.com/%(owner)s/opendxl-client-python@epo-legacy"
pip install "dxlbootstrap @ git+https://github.com/%(owner)s/opendxl-bootstrap-python@master"
pip install .          # or the downstream project
```

Measured: with that order a downstream project's environment ends up with `dxlclient
5.7.0.1+fork.1` and `msgpack 1.2.2`; with a plain `pip install .` it gets the published client
and `msgpack 0.6.2`. Every CI workflow in the fork does it in this order.

Pick the client branch that matches your fabric:

| Branch | Cipher default | For |
|---|---|---|
| `master` | Forward-secrecy suites only | ePO 5.10 SP1 U7+ / DXL 6.1.1+ |
| `epo-legacy` | Forward secrecy first, `AES128-SHA256` as fallback | Older fabrics and the open source broker |
| `fix/python3-modernization` | - | Shared fix history; tracks `epo-legacy` |

**Java** - the jars from the releases (the `-all` jar is the shaded one the provisioning CLI
runs from), this repository's GitHub Packages Maven registry, or `./gradlew
publishToMavenLocal` from a clone. Coordinates stay `com.opendxl:dxlclient`, version
`0.2.9-fork.1` on `master` (JDK 21) and `0.2.9-fork.1-jdk17` / `-jdk11` / `-jdk8` on the
branch for each JDK line - the four lines build different bytecode and cannot share one set
of coordinates.

**JavaScript** - the tarball from the releases:

```bash
npm install https://github.com/%(owner)s/opendxl-client-javascript/releases/download/v0.1.4+fork.1/opendxl-dxl-client-0.1.4+fork.1.tgz
```

It keeps the name `@opendxl/dxl-client`, and `+fork.1` is semver *build metadata*, which is
ignored when matching ranges - so it satisfies the `^0.1.x` dependency the downstream packages
(`node-red-contrib-dxl-*`, the ePO/TIE/MAR client libraries) declare and replaces the
published 0.1.4 with its `mqtt` 2.x tree in an existing install.

**Broker** - pull `ghcr.io/%(owner)s/opendxl-broker:latest` (or `:almalinux`), or build the
image from the fork; `DXL_TLS_MODE` then selects the cipher profile. See
[TLS and ciphers](broker/tls.md#fixing-it-on-the-broker).

## Known caveats

- **The releases are not on the public registries**, by design (see above). Consuming them
  means a URL, a GitHub Packages registry entry, or a git reference - not a bare
  `pip install dxlclient`.
- **Not offered upstream yet.** No pull request has been opened against
  `opendxl/opendxl-client-python`. The core repositories do have active maintainers, so this
  is a question of getting the changes in front of them, not of whether anyone is there.
- **This is a personal fork.** It is not an official Trellix distribution, carries no support
  commitment, and may stop being maintained. Treat it as you would any single-maintainer
  dependency: read the diff, pin a commit, and be ready to carry it yourself.
"""


def main():
    data = json.load(open(DATA, encoding='utf-8'))
    body = (header(data) + highlights(data) + '\n' + per_repo(data) + '\n' +
            FOOTER % {'owner': data['fork_owner_account']})
    misattributed = data['totals']['misattributed_commits']
    if misattributed:
        body += ('- **%d early commits carry a stale author** (`Bot <bot@example.com>` rather '
                 'than `%s`).\n' % (misattributed, data['author']))
    open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
    print('wrote %s (%d commits, %d repositories)'
          % (OUT, data['totals']['commits'], data['totals']['repositories_touched']))


if __name__ == '__main__':
    main()
